version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - persist_to_workspace:
          root: my_workspace
          paths:
            - echo-output
  test-1:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - attach_workspace:
          at: my_workspace
      - run: cat my_workspace/echo-output
  test-2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - attach_workspace:
          at: my_workspace
      - run: echo "Then Test-2"
      - run: |
          if [[ $(cat my_workspace/echo-output) == 'Trying out workspaces' ]]; then
            echo "It worked!";
          else
            echo "It failed!"; exit 1
          fi

  deploy:  
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - attach_workspace:
          at: my_workspace
      - run: echo "Finally Deploy"
      - run: cat my_workspace/echo-output

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-1:
          requires:
            - build
      - test-2:
          requires:
            - build
      - deploy:
          requires:
            - test-1
            - test-2
