version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello Build"
  test-1:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Then Test-1"
      - run: sleep 5
  test-2:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Then Test-2"
      - run: sleep 5
  deploy:  
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Finally Deploy"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-1:
          requires:
            - build
      - test-2:
          requires:
            - build
      - deploy:
          requires:
            - test-1
            - test-2
